"""empty message

Revision ID: 446396f173a5
Revises: c0ced1692df3
Create Date: 2025-10-01 06:52:09.528635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446396f173a5'
down_revision: Union[str, Sequence[str], None] = 'c0ced1692df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('total', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric', 'total')
    # ### end Alembic commands ###
