"""empty message

Revision ID: c0ced1692df3
Revises: d43841b3d37c
Create Date: 2025-09-22 20:20:36.353668

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0ced1692df3"
down_revision: Union[str, Sequence[str], None] = "d43841b3d37c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "server",
        sa.Column(
            "top_five_processes", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "top_five_processes")
    # ### end Alembic commands ###
